# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99a3fd8527f4e9380e2b2c97f4f5242460c6aac28e4893bbcf9f1c43ec317a4ef3bfa986038beb5884cb29f48beeb2613e46c5ac893d5aaadaaff51b98348f4e

test:
  secret_key_base: ec098930b909deac28b78e6d18309377e1b7473feee4e4f2b54a74eacc1143db4b433e6c22336fe3e7901c921194f3eb38ac609435b629fc40c0e6aa8e51ccb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
